CREATE TABLE IF NOT EXISTS users (
    userName VARCHAR(255) PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS rooms (
    roomName VARCHAR(255) PRIMARY KEY
    );

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    roomName VARCHAR(255) NOT NULL,
    userName VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL,
    FOREIGN KEY(roomName) REFERENCES rooms(roomName),
    FOREIGN KEY(userName) REFERENCES users(userName)
    );